/* ===========================================================
   SRI HARI INDUSTRIES — Our Clients section
   --------------------------------------------------------
   EDIT CONTENT HERE.

   CLIENTS — the real brands / establishments you supply.
   Each client is either:
     • a LOGO card  → give it a `logo` path (image in
       /public/images/clients/…). Shown grayscale, turns
       full-colour on hover (clean, professional look).
     • a NAME card  → omit `logo`. Shown as a styled wordmark
       (use `accent` to colour the last word green).

   To ADD a client: copy a line into CLIENTS below.
   To ADD a logo image: drop the file in
       web/public/images/clients/<name>.png
   and set  logo: '/images/clients/<name>.png'

   (The kinds of kitchens we serve live in the separate
   "Industries We Serve" section — Services.tsx.)
   =========================================================== */

type Client = {
  name: string;           // full display / alt text
  logo?: string;          // /images/clients/xxx.png  → renders logo card
  accent?: string;        // last word to tint green on a NAME card (optional)
};

// ---- Real clients (mix of logos + names) ----
const CLIENTS: Client[] = [
  // Placeholder icon+wordmark SVGs (generated by scripts/gen-client-logos.mjs).
  // Replace each file in web/public/images/clients/ with the client's REAL
  // logo when you have it — keep the same file name and it updates automatically.
  { name: 'Mahindra', logo: '/images/clients/mahindra.svg' },
  { name: 'Annapurna', logo: '/images/clients/annapurna.svg' },
  { name: 'Annathanes', logo: '/images/clients/annathanes.svg' },
  { name: 'Sri Krishna', logo: '/images/clients/sri-krishna.svg' },
  { name: 'Saravana', logo: '/images/clients/saravana.svg' },
  { name: 'Anandhaas', logo: '/images/clients/anandhaas.svg' },
  { name: 'Vasanta', logo: '/images/clients/vasanta.svg' },
  { name: 'Grand', logo: '/images/clients/grand.svg' },
  { name: 'Aryaas', logo: '/images/clients/aryaas.svg' },
  { name: 'Sangeetha', logo: '/images/clients/sangeetha.svg' },
];

// Split "Anna Thanes" → "Anna" + "Thanes" so a name card can tint the last word.
function nameParts(c: Client) {
  const words = c.name.trim().split(/\s+/);
  if (c.accent) {
    return { lead: c.name.slice(0, c.name.length - c.accent.length).trim(), tail: c.accent };
  }
  if (words.length > 1) {
    return { lead: words.slice(0, -1).join(' '), tail: words[words.length - 1] };
  }
  return { lead: '', tail: c.name };
}

// One glass card (logo or wordmark). `dup` marks the seamless-loop copies so
// they're hidden from assistive tech and collapsed when motion is reduced.
function renderCard(c: Client, key: string, dup: boolean) {
  const aria = dup ? ({ 'aria-hidden': true } as const) : {};
  if (c.logo) {
    return (
      <div className="logocard" key={key} title={c.name} {...aria}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={c.logo} alt={dup ? '' : c.name} loading="lazy" />
      </div>
    );
  }
  const { lead, tail } = nameParts(c);
  return (
    <div className="logocard logocard--name" key={key} title={c.name} {...aria}>
      <span className="logocard__name">
        {lead && <>{lead} </>}
        <span>{tail}</span>
      </span>
    </div>
  );
}

export function Clients() {
  const rev = [...CLIENTS].reverse(); // second row flows the other way

  return (
    <section className="sec" id="clients">
      <div className="wrap">
        <div className="clients__head reveal">
          <span className="eyebrow eyebrow--g">Our Clients</span>
          <h2>Some of our valuable clients</h2>
          <p>Trusted by leading restaurants, hotels &amp; institutions across South India</p>
        </div>

        {/* ---- Two-row infinite logo marquee (flows opposite ways, pauses on
               hover, fades at the edges). Each row is doubled for a seamless
               loop; the duplicate half is aria-hidden. ---- */}
        <div className="cmar reveal" aria-label="Some of our clients">
          <div className="cmar__row">
            <div className="cmar__track">
              {CLIENTS.map((c, i) => renderCard(c, `a1-${i}`, false))}
              {CLIENTS.map((c, i) => renderCard(c, `a2-${i}`, true))}
            </div>
          </div>
          <div className="cmar__row cmar__row--rev" aria-hidden="true">
            <div className="cmar__track">
              {rev.map((c, i) => renderCard(c, `b1-${i}`, true))}
              {rev.map((c, i) => renderCard(c, `b2-${i}`, true))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
